export const videosDb = [
  {
    id: 1,
    category: 'Front End',
    imgSrc: '../imgs/frontend--1.jpg',
    videoSrc: 'https://www.youtube.com/watch?v=Z-N5Fr9P-GU',
    title: '',
    description: '',
    user: '',
  },
  {
    id: 2,
    category: 'Front End',
    imgSrc: '../imgs/frontend--2.jpg',
    videoSrc: 'https://www.youtube.com/watch?v=6IuQUgeDPg0',
    title: '',
    description: '',
    user: '',
  },
  {
    id: 3,
    category: 'Front End',
    imgSrc: '../imgs/frontend--3.jpg',
    videoSrc: 'https://www.youtube.com/watch?v=KdQa4Rd6K1A',
    title: '',
    description: '',
    user: '',
  },
  {
    id: 4,
    category: 'Front End',
    imgSrc: '../imgs/frontend--4.png',
    videoSrc: 'https://www.youtube.com/watch?v=KdQa4Rd6K1A',
    title: '',
    description: '',
    user: '',
  },
  {
    id: 5,
    category: 'Data Science',
    imgSrc: '../imgs/dataScience--1.jpg',
    videoSrc: 'https://www.youtube.com/watch?v=Kk3vBRqKA2o',
    title: '',
    description: '',
    user: '',
  },
  {
    id: 6,
    category: 'Data Science',
    imgSrc: '../imgs/dataScience--2.jpg',
    videoSrc: 'https://www.youtube.com/watch?v=K-eaT4V8j-w',
    title: '',
    description: '',
    user: '',
  },
  {
    id: 7,
    category: 'Data Science',
    imgSrc: '../imgs/dataScience--3.jpg',
    videoSrc: 'https://www.youtube.com/watch?v=qYhixp5qxTc',
    title: '',
    description: '',
    user: '',
  },
  {
    id: 8,
    category: 'Data Science',
    imgSrc: '../imgs/dataScience--4.png',
    videoSrc: 'https://www.youtube.com/watch?v=AE214uRJ2UQ',
    title: '',
    description: '',
    user: '',
  },
  {
    id: 9,
    category: 'Mobile',
    imgSrc: '../imgs/mobile--1.jpg',
    videoSrc: 'https://www.youtube.com/watch?v=4AH9H_dx_7g',
    title: '',
    description: '',
    user: '',
  },
  {
    id: 10,
    category: 'Mobile',
    imgSrc: '../imgs/mobile--2.jpg',
    videoSrc: 'https://www.youtube.com/watch?v=uXA8jLSuPNA',
    title: '',
    description: '',
    user: '',
  },
  {
    id: 11,
    category: 'Mobile',
    imgSrc: '../imgs/mobile--3.jpg',
    videoSrc: 'https://www.youtube.com/watch?v=ly8e6WB0YQo',
    title: '',
    description: '',
    user: '',
  },
  {
    id: 12,
    category: 'Mobile',
    imgSrc: '../imgs/mobile--4.png',
    videoSrc:
      'https://learn.microsoft.com/en-us/shows/xamarinshow/xamarinforms-101-xaml-previewer',
    title: '',
    description: '',
    user: '',
  },
]

export const categoriesDb = [
  {
    id: 1,
    categoryName: 'Front End',
    categoryDescription: 'Formação Front End da Alura',
    color: '#6BD1FF',
  },
  {
    id: 2,
    categoryName: 'Data Science',
    categoryDescription: 'Formação Data Science da Alura',
    color: '#69953B',
  },
  {
    id: 3,
    categoryName: 'Mobile',
    categoryDescription: 'Formação Mobile da Alura',
    color: '#FFBA05',
  },
]
